#!/usr/bin/env zsh
#
# Install script for dwn utility.
#
#
# Author: Brandon Lepore <https://github.com/fatherbrennan>
# Date: June 05, 2025
# License: MIT

# set permissions of script files in bin directory.
# important because cp will preserve permissions later.
set_bin_dir_permissions() {
  INSTALLER_STEP=permissions

  chmod 755 "./bin/$PROG_NAME" || log_error_exit $E_PERMISSIONS_BIN_DIR
  log "$PROG_NAME permissions set!"
}

# add environment variables to zsh.
# case handlers:
# - no ~/.zshrc file.
# - env variables already exist.
set_env_vars() {
  INSTALLER_STEP=env_vars
  local env_vars_text="\n$ENV_VARIABLES_TEXT"

  # check if the file exists.
  if [[ -f "$FILE_ZSHRC" ]]; then
    # append text if not in file.
    if ! grep -qzo "$ENV_VARIABLES_TEXT" "$FILE_ZSHRC"; then
      printf "$env_vars_text" >>"$FILE_ZSHRC" ||
         log_error_exit $E_ENV_VARS_APPEND
    else
      log 'environment variables already exist!'
    fi
  else
    # create file with text.
    printf "$env_vars_text" >"$FILE_ZSHRC" || log_error_exit $E_ENV_VARS_WRITE
    log 'environment variables added!'
  fi

  # make sure to make new variables available.
  source "$FILE_ZSHRC" || log_error_exit $E_ENV_VARS_SOURCE
}

# create config directory.
set_config_dir() {
  INSTALLER_STEP=config_dir

  if [[ ! -d "$DWN_INSTALL" ]] || bool $DEV_MODE; then
    # assume fresh install if no directory.
    mkdir -p -m 755 $DWN_INSTALL
    cp -Rp ./bin $DWN_INSTALL
    log "created: $DWN_INSTALL"
  else
    # log "Directory exists"
    # # check version file.
    # if [[ -f $version_file ]]; then
    # local version_file="$DWN_INSTALL/$FILE_DWN_VERSION"
    # local version_pattern="^[0-9]+\.[0-9]+\.[0-9]+$"
    # local version=""
    #   log "Version file exists"
    #   version=$(head -n 1 "$version_file")
    #   if [[ "$version" =~ $version_pattern ]]; then
    #     log "Version file is valid"
    #     if [[ "$version" != "$PROG_VERSION" ]]; then
    #       log "Different version"
    #     fi
    #   else
    #     # do something if not valid version
    #   fi
    # else
    #   log "Version file does not exist"
    # fi
    # log 'unsupported operation for now' && exit 0
  fi
}

main() {
  source ./common
  INSTALLER_LOG=install

  set_os
  set_bin_dir_permissions
  set_env_vars
  set_config_dir

  cat <<-EOF
installed $PROG_NAME
=> v$PROG_VERSION
to check if the installation was successful, use

    $PROG_NAME -v

EOF

  return 0
}

main
